---
title: Population data
output: github_document
---

The purpose of this document is to write out the 2019 estimate for the population of Iowa counties. 

The source of this data is the [Iowa Community Indicators Program](https://www.icip.iastate.edu/tables/population/counties-estimates).

```{r packages}
library("fs")
library("magrittr")
library("iowa.covid")
library("dplyr")
library("readr")
```

```{r dir}
dir_create("data")

dir_target <- path("data", "population")
dir_create(dir_target)
```

```{r}
county_closed <- 
  c(
    "Allamakee", 
    "Benton", 
    "Black Hawk", 
    "Bremer", 
    "Dallas", 
    "Des Moines", 
    "Dubuque", 
    "Fayette", 
    "Henry", 
    "Iowa", 
    "Jasper", 
    "Johnson", 
    "Linn", 
    "Louisa", 
    "Marshall", 
    "Muscatine", 
    "Polk", 
    "Poweshiek", 
    "Scott", 
    "Tama", 
    "Washington", 
    "Woodbury"
  )
```


```{r}
iowa_county_meta <-
  iowa_county_population %>%
  select(fips, county, population, population_group) %>%
  mutate(
    opening = 
      ifelse(county %in% county_closed, "2020-05-15", "2020-05-01") %>%
      as.Date()
  ) %>%
  glimpse()
```

```{r}
write_csv(
  iowa_county_meta, 
  path(dir_target, "iowa_county_meta.csv")
)
```
