on:
  push:
    paths:
      - README.Rmd

  schedule:
    # run at 16h00 UTC (11h00 Iowa, daylight-saving-time)
    - cron:  '00 16 * * *'

name: Get data

jobs:
  render:
    name: Get data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Get population file
        run: |
          Rscript -e 'rmarkdown::render("00-population.Rmd")'
          ls -l -R data/population

      - name: Get HTML file
        run: |
          Rscript -e 'rmarkdown::render("01-scrape-iowa-site.Rmd")'
          ls -l -R data/download-site

      - name: Get NYT county-data
        run: |
          Rscript -e 'rmarkdown::render("02-get-nyt-data.Rmd")'
          ls -l -R data/nyt

      - name: Git commit & push
        run: |
          git add '*.md'
          git add 'data/nyt/nyt-iowa.csv'
          git add 'data/population/iowa_county_population.csv'
          git add 'data/download-site/*'
          git commit -m 'daily run' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

