on:
  push:
    paths:
      - README.Rmd

name: Render README

jobs:
  render:
    name: Get HTML file
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Find chrome
        run: |
          export HEADLESS_CHROME=$(Rscript -e 'cat(pagedown::find_chrome()[[1]])')
          echo $HEADLESS_CHROME

      - name: Render file
        run: |
          Rscript -e 'rmarkdown::render("01-scrape-iowa-site.Rmd")'
          sleep 30
          ls -l data/download-site

